# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 7540feb001a8225ab5f01251d03bb88d60917813f56a9386d09f98006f3ceb17753c99a777bc6e8bd1df029f36352ea7f04c7c7dced66df5b2b46f4e4c4f0565

test:
  secret_key_base: 45435b545caffd1341102f67a4dd17e657624a941f47a29f688c52dcb7e6df0283a876eb029251ccde4916f0e3e317fc622d36df3cda6a47894dd155bc8febb3

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
